spring.batch.job.name: ${jobName:NONE}
spring:
  profiles:
    active: local

---
spring.config.activate.on-profile: local
spring:
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring.config.activate.on-profile: mysql
spring:
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:13306/spring_batch
      username: root
      password: 12345678
      driver-class-name: com.mysql.jdbc.Driver